package SalesReport; 

//import required java libraries
import java.io.*;
import java.util.*; //this import is to use data structures like Map and list

public class Main { //the program it will star in this part of public class
    public static void main(String[] args) {
        generateSellerSalesReportCSV(); //this will be the method to generate the report
    }

    //this method it will let us have the information of the sellers (sales, total organized) in the CSV file
    public static void generateSellerSalesReportCSV() {
        //this map it will read the prices, in this case we will use the product ID and prince
        Map<String, Double> productPrices = new HashMap<>();

        //this part it will try to review the product information that is listed on the .txt files generated by the class "GenerateInfoFiles"
        try (BufferedReader br = new BufferedReader(new FileReader("data_output/productsFile.txt"))) {
            String line;
            while ((line = br.readLine()) != null) { //review the file line over line
                String[] parts = line.split(";"); //this part it will divide the information using ; as it says on the homework
                String id = parts[0]; //this will organize the product ID in the first field
                double price = Double.parseDouble(parts[2]); //this will organize the total price in the 3 field
                productPrices.put(id, price); //this part of the code ir will add product and price
            }
        } catch (IOException e) { //If we have an error reading the .txt it will run this validation
            System.out.println("Error reading productsFile.txt: " + e.getMessage());
            return; 
        }

        //this map it will put the seller name validating the document ID
        Map<String, String> sellers = new HashMap<>();
        try (BufferedReader br = new BufferedReader(new FileReader("data_output/infoSellers.txt"))) {
            String line;
            while ((line = br.readLine()) != null) { //review the file line over line
                String[] parts = line.split(";"); //this part it will divide the information using ; as it says on the homework
                String documentId = parts[1]; //this will organize the seller ID in the second field
                String fullName = parts[2] + " " + parts[3]; //will put the full name
                sellers.put(documentId, fullName); //save the map ID = name + name
            }
        } catch (IOException e) { //If we have an error reading the .txt it will run this validation
            System.out.println("Error reading infoSellers.txt: " + e.getMessage());
            return; 
        }

        //this map it will be creating to sum the total seller information. To get how much of sales does he have
        Map<String, Double> sellerRevenue = new HashMap<>();

        //loop in all salesMen_X.txt files in the folder data_output
        File folder = new File("data_output"); //check on the main folder where we organized the information
        File[] files = folder.listFiles(); //review all the files that are listed

        if (files != null) { //validator if the folder is not empty
            for (File file : files) { //for each file in the folder
                if (file.getName().startsWith("salesMen_")) { //this if it will process only sales files not the others
                    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                        String documentLine = br.readLine(); //in the first line it will be the seller info / the document
                        String documentId = documentLine.split(";")[1]; //it will extract the document Id
                        String sellerName = sellers.get(documentId); //validate the seller name based on the id

                        if (sellerName == null) {
                            continue; //if it does not found the seller it will skip the seller info
                        }

                        String line;
                        double total = 0.0; //this part it will complete the sum up of sales

                        while ((line = br.readLine()) != null) { //this part it will read the product sales
                            String[] parts = line.split(";"); //this part it will split the info
                            String productId = parts[0]; //product id 
                            int quantity = Integer.parseInt(parts[1]); //total of products sold
                            double price = productPrices.getOrDefault(productId, 0.0); //cost
                            total += quantity * price; //add subtotal to total
                        }

                        //update seller's total revenue (add to previous if exists)
                        sellerRevenue.put(sellerName,
                                sellerRevenue.getOrDefault(sellerName, 0.0) + total);

                    } catch (IOException e) {
                        System.out.println("Error reading sales file: " + file.getName());
                    }
                }
            }
        }

        //this part of the map it will allow us to organize the seller total sold from highest to lowest
        List<Map.Entry<String, Double>> sortedList = new ArrayList<>(sellerRevenue.entrySet());
        sortedList.sort((a, b) -> Double.compare(b.getValue(), a.getValue())); // Sort descending

        //write the information organized in the CSV file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data_output/seller_sales_report.csv"))) {
            for (Map.Entry<String, Double> entry : sortedList) { //loop on the organized information from sellers
                String line = entry.getKey() + ";" + String.format("%.2f", entry.getValue()); //the format that was set up in this case was name;amount
                writer.write(line); //write the information
                writer.newLine(); //move to next line
            }
            System.out.println("Report generated correclty: seller_sales_report.csv");
        } catch (IOException e) { //review the information and if found an error print error message
            System.out.println("Error writing seller_sales_report.csv: " + e.getMessage());
        }
    }
}
